import type { Metadata } from "next";
import '@/views/style/global.scss'
import { NavigationPanel } from "@/features/navigation-panel/NavigationPanel";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className='max-w-screen max-h-screen w-full h-full bg-[#E3E5E8] overflow-hidden'>
      <div className="w-full h-full flex sm:flex-row flex-col-reverse p-[7px] overflow-hidden">
        <NavigationPanel />
        <main className="w-full h-full bg-white rounded-[20px] overflow-hidden">
          {children}
        </main>
      </div>
    </section>
  );
}
