import type { Metadata } from "next";
import '@/views/style/global.scss'
import { Inter } from "next/font/google";
import { Provider } from "@/shared/ui/provider/Provider";
import { Header } from "@/widgets/header/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
